# modules/monitoring/variables.tf
# Inputs for the monitoring layer: SNS, Route53 health checks, CloudWatch alarms.

variable "name_prefix" {
  description = "Prefix applied to all resource names."
  type        = string
}

variable "alarm_email" {
  description = "Email subscribed to the SNS alarm topics (confirm manually)."
  type        = string
}

variable "daily_cost_threshold_usd" {
  description = "USD spent in a single day (day-over-day EstimatedCharges delta) above which the daily cost alarm fires."
  type        = number
}

# One entry per workload to monitor (e.g. app, jenkins). Per-service alarms and
# Route53 health checks are generated by iterating this map.
variable "services" {
  description = "Services to monitor, keyed by short name."
  type = map(object({
    alb_arn_suffix    = string # CloudWatch LoadBalancer dimension (5xx/4xx)
    alb_dns_name      = string # Route53 health-check target
    cluster_name      = string # ECS ClusterName dimension (CPU/memory)
    service_name      = string # ECS ServiceName dimension (CPU/memory)
    health_check_path = string # HTTP path probed by the Route53 health check
  }))
}

variable "cpu_threshold_percent" {
  description = "ECS service CPU utilization (%) above which the CPU alarm fires."
  type        = number
  default     = 80
}

variable "memory_threshold_percent" {
  description = "ECS service memory utilization (%) above which the memory alarm fires."
  type        = number
  default     = 80
}

variable "target_4xx_threshold" {
  description = "Target 4xx count over a 5-minute window above which the 4xx alarm fires. 4xx are client errors, so this is a spike threshold rather than > 0."
  type        = number
  default     = 100
}
